name: Build and push 2.x images

on:
  push:
    branches:
      - 'main'
      - 'next'
    tags:
      - 'v2.*'

jobs:
  docker:
    environment: 'Docker Push'
    runs-on: ubuntu-latest
    steps:
      - name: Parse semver string
        id: semver_parser
        if: ${{ contains(github.ref, 'tags') }}
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: 'refs\/tags\/v(.*)$'
      - name: Read latest_version
        id: latest_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./latest_version
      - name: Add standard tags
        run: |
          echo 'TAGS_STANDARD<<EOF' >> $GITHUB_ENV
          echo 'type=ref,event=branch' >> $GITHUB_ENV
          echo 'type=semver,pattern={{version}}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Add major.minor tag
        if: ${{ steps.semver_parser.outputs.prerelease == '' }}
        run: |
          echo 'TAGS_SUPPLEMENTAL<<EOF' >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo 'type=semver,pattern={{major}}.{{minor}}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: traines/kic
          flavor: |
            latest=${{ steps.semver_parser.outputs.fullversion == steps.latest_version.outputs.content }}
          tags: ${{ env.TAGS_STANDARD }}${{ env.TAGS_SUPPLEMENTAL }}
      - name: Build binary
        env:
          TAG: ${{ steps.meta.outputs.version }}
          COMMIT: ${{ github.sha }}
          REPO_INFO: https://github.com/${{ github.repository }}.git
        id: docker_build_binary
        uses: docker/build-push-action@v2
        with:
          push: false
          file: Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: builder
      - name: Build and push
        id: docker_build
        env:
          TAG: ${{ steps.meta.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
