name: 'Check for license changes'

on: [pull_request]

#defaults:
  #run:
  #  working-directory: ${{ env.GOPATH }}/src/github.com/Kong/
jobs:
  licenses:
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Install go-licenses
      run: go get github.com/google/go-licenses
    - name: Create source location
      run: mkdir -p ${{ github.workspace }}/src/github.com/Kong/
    - name: Checkout target
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        path: ${{ github.workspace }}/src/github.com/Kong/kubernetes-ingress-controller
    - name: Generate target license report
      run: go-licenses csv ./cli/ingress-controller/ | sort > ${{ github.workspace }}/target_licenses.csv
      working-directory: ${{ github.workspace }}/src/github.com/Kong/kubernetes-ingress-controller
    - name: Clear target
      run: rm -rf ${{ github.workspace }}/src/github.com/Kong/kubernetes-ingress-controller
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/src/github.com/Kong/kubernetes-ingress-controller
    - name: Generate PR license report
      run: go-licenses csv ./cli/ingress-controller/ | sort > ${{ github.workspace }}/pr_licenses.csv
      working-directory: ${{ github.workspace }}/src/github.com/Kong/kubernetes-ingress-controller
    - name: Compare license reports
      id: compare_reports
      run: |
        DIFFOUT=$(diff -u target_licenses.csv pr_licenses.csv)
        echo "::set-output name=diff::${DIFFOUT//$'\n'/'%0A'}"
    - name: Update PR if different
      uses: actions/github-script@v3
      env:
        DIFF_OUTPUT: ${{ steps.compare_reports.outputs.diff }}
      if: ${{ steps.compare_reports.outputs.diff != '' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Licenses differ between PR and base:\n' + process.env.DIFF_OUTPUT
            })

