name: 'Check for license changes'

on: [pull_request]

jobs:
  licenses:
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Install go-licenses
      run: go get github.com/google/go-licenses
    - name: Create source location
      run: mkdir -p src/github.com/Kong/
    - name: Checkout target
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        path: src/github.com/Kong/kubernetes-ingress-controller
    - name: Generate target license report
      run: go-licenses csv ./cli/ingress-controller/ | sort > ${{ github.workspace }}/target_licenses.csv
      working-directory: src/github.com/Kong/kubernetes-ingress-controller
    - name: Clear target
      run: rm -rf src/github.com/Kong/kubernetes-ingress-controller
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        path: src/github.com/Kong/kubernetes-ingress-controller
    - name: Generate PR license report
      run: go-licenses csv ./cli/ingress-controller/ | sort > ${{ github.workspace }}/pr_licenses.csv
      working-directory: src/github.com/Kong/kubernetes-ingress-controller
#   - name: Compare license reports
#     id: compare_reports
#     run: |
#       echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
#       curl https://httpbin.org/json >> $GITHUB_ENV
#       echo 'EOF' >> $GITHUB_ENV
#       echo "::set-output name=diff::$JSON_RESPONSE"
#   - name: Compare license reports
#     id: compare_reports
#     run: |
#       echo 'DIFF_OUT<<EOF' >> $GITHUB_ENV
#       diff -u target_licenses.csv pr_licenses.csv >> $GITHUB_ENV
#       echo 'EOF' >> $GITHUB_ENV
#       echo "::set-output name=diff::$DIFF_OUT"
    - name: Compare license reports
      id: compare_reports
      run: |
        DIFF_OUT=$(diff -u target_licenses.csv pr_licenses.csv)
        echo "::set-output name=diff::$DIFF_OUT"
    - name: Update PR if licenses differ
      uses: actions/github-script@v3
      env:
        DIFF_OUTPUT: ${{ steps.compare_reports.outputs.diff }}
      if: ${{ steps.compare_reports.outputs.diff != '' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Licenses differ between PR and base:\n' + process.env.DIFF_OUTPUT
            })

