name: 'Check for license changes'

on: [pull_request]

#defaults:
  #run:
  #  working-directory: ${{ env.GOPATH }}/src/github.com/Kong/
jobs:
  licenses:
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go
    - name: Install go-licenses
      run: go get github.com/google/go-licenses
    - name: Create source location
      run: mkdir /src/github.com/Kong/
    - name: Checkout target
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        path: /src/github.com/Kong/kubernetes-ingress-controller
    - name: Generate target license report
      run: go-licenses csv ./cli/ingress-controller/ > /target_licenses.csv
      working-directory: /src/github.com/Kong/kubernetes-ingress-controller
    #- name: Checkout PR
    #  uses: actions/checkout@v2
    #  with:
    #    path: /src/github.com/Kong/
    #- name: Generate PR license report
    #  run: go-licenses csv ./cli/ingress-controller/ > /tmp/pr_licenses.csv
    - name: stub
      run: cat /target_licenses.csv

